CREATE TABLE Airlines (
    Code VARCHAR(10) PRIMARY KEY,
    Description VARCHAR(100)
);

CREATE TABLE FlightsBS (
    FlightDate DATE,
    Airline VARCHAR(100),
    Origin VARCHAR(100),
    Dest VARCHAR(100),
    Cancelled BOOLEAN,
    Diverted BOOLEAN,
    CRSDepTime INT,
    DepTime FLOAT,
    DepDelayMinutes FLOAT,
    DepDelay FLOAT,
    ArrTime FLOAT,
    ArrDelayMinutes FLOAT,
    AirTime FLOAT,
    CRSElapsedTime FLOAT,
    ActualElapsedTime FLOAT,
    Distance FLOAT,
    Year INT,
    Quarter INT,
    Month INT,
    DayofMonth INT,
    DayOfWeek INT,
    Marketing_Airline_Network VARCHAR(100),
    Operated_or_Branded_Code_Share_Partners VARCHAR(100),
    DOT_ID_Marketing_Airline INT,
    IATA_Code_Marketing_Airline VARCHAR(100),
    Flight_Number_Marketing_Airline INT,
    Operating_Airline VARCHAR(255) FOREIGN KEY REFERENCES Airlines(Code),
    DOT_ID_Operating_Airline INT,
    IATA_Code_Operating_Airline VARCHAR(100),
    Tail_Number VARCHAR(100),
    Flight_Number_Operating_Airline INT,
    OriginAirportID INT,
    OriginAirportSeqID INT,
    OriginCityMarketID INT,
    OriginCityName VARCHAR(100),
    OriginState VARCHAR(100),
    OriginStateFips INT,
    OriginStateName VARCHAR(100),
    OriginWac INT,
    DestAirportID INT,
    DestAirportSeqID INT,
    DestCityMarketID INT,
    DestCityName VARCHAR(100),
    DestState VARCHAR(100),
    DestStateFips INT,
    DestStateName VARCHAR(100),
    DestWac INT,
    DepDel15 FLOAT,
    DepartureDelayGroups FLOAT,
    DepTimeBlk VARCHAR(100),
    TaxiOut FLOAT,
    WheelsOff FLOAT,
    WheelsOn FLOAT,
    TaxiIn FLOAT,
    CRSArrTime INT,
    ArrDelay FLOAT,
    ArrDel15 FLOAT,
    ArrivalDelayGroups FLOAT,
    ArrTimeBlk VARCHAR(100),
    DistanceGroup INT,
    DivAirportLandings INT
);

